Authentication_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from website.views.website_front import *

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^registration/', include('registration.urls')),
    url(r'^website/', include('website.urls')),
    url(r'^survey/', include('SurveyApp.urls')),
    url(r'^$', HomePage.as_view(), name='index'),
    url(r'^pricing', PricingPage.as_view(), name='pricing'),
]

registration/urls.py
from django.conf.urls import url
from registration import views

app_name = 'registration'
urlpatterns = [
    url(r'^hr_register/$', views.registerHR, name='hr_register'),
    url(r'^manager_register/$', views.registerManager, name="manager_register"),
    url(r'^auth_HRlogin/$', views.HR_login, name='HRlogin'),
    url(r'^update/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.CandidateSignIn, name='CandidateSignIn'),
    url(r'^auth_logout/$', views.user_logout, name='logout'),
    url(r'^project/(?P<pk1>[0-9]+)/auth_team_register3/$',
        views.TeamRegister2, name='team_register3'),
    url(r'^project/(?P<pk1>[0-9]+)/auth_applicant_register3/$',
        views.applicantregister2, name='applicant_register3'),

]

website/urls.py
from django.conf.urls import url, include
from website.views import *
from website import views

app_name = 'website'
urlpatterns = [
    url(r'^hr_index/$', HRIndex.as_view(), name='hr_index'),
    url(r'^create_project/$', CreateProject.as_view(), name='create_project'),
    url(r'^candidate_index/$', CandidateIndex.as_view(),name='candidate_index'),
    url(r'^employee_index/(?P<pk2>[0-9]+)/$', EmployeeIndex.as_view(),name='employee_index'),
    url(r'^addproject/$', ProjectCreate.as_view(), name='add_project'),
    url(r'^project/(?P<pk1>[0-9]+)/create_team/$', CreateTeam.as_view(), name='create_team'),
    url(r'^project/(?P<pk1>[0-9]+)/addteam/$', TeamCreate.as_view(), name='add_team'),
    #url(r'^project/(?P<pk1>[0-9]+)/linkteam2/$', TeamSelect, name='team_select'),
    url(r'^project/(?P<pk1>[0-9]+)/$',ProjectDetailView.as_view(), name='ProjectDetails'),
    url(r'^project/(?P<pk1>[0-9]+)/api/chart/data2/$',TeamChartData.as_view(), name='TeamChartData'),
    url(r'^project/employee/(?P<pk1>[0-9]+)/(?P<pk2>[0-9]+)/$',EmployeeDetailView.as_view(), name='EmployeDetails'),
    url(r'^project/applicant/(?P<pk1>[0-9]+)/(?P<pk2>[0-9]+)/$',CandidateDetailView.as_view(), name='CandidateDetails'),
    url(r'^project/employee/(?P<pk1>[0-9]+)/(?P<pk2>[0-9]+)/api/chart/data/$',EmployeeChartData.as_view(), name='EmployeeChartData'),
    url(r'^project/applicant/(?P<pk1>[0-9]+)/(?P<pk2>[0-9]+)/api/chart/data3/$',applicantChartData.as_view(), name='CandidateChartData'),
    url(r'^project/(?P<pk1>[0-9]+)/recruitment/$', RecruitmentPage.as_view(), name='recruitment'),
    url(r'^payment_form/$', payment_form.as_view(), name='payment'),
    url(r'^checkout/$', views.checkout, name="checkout_page"),
]

survey/models/response.py
# -*- coding: utf-8 -*-

from __future__ import (
    absolute_import, division, print_function, unicode_literals
)

from builtins import object

from registration.views import MyUser
from django.db import models
from django.utils.translation import ugettext_lazy as _
from future import standard_library

from .survey import Survey

standard_library.install_aliases()


class Response(models.Model):

    """
        A Response object is a collection of questions and answers with a
        unique interview uuid.
    """

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    survey = models.ForeignKey(Survey, related_name="responses")
    user = models.ForeignKey(MyUser, null=True, blank=True)
    interview_uuid = models.CharField(_(u"Interview unique identifier"),
                                      max_length=36)

    class Meta(object):
        verbose_name = _('response')
        verbose_name_plural = _('responses')

    def __str__(self):
        msg = u"Response id {} to {} by {}".format(self.id,self.survey, self.user)
        #msg += u" on {}".format(self.created)
        return msg

website/forms.py
from django import forms
from django.contrib.auth.models import User
from registration.models import MyUser
from .models import Team
from django.contrib.auth import get_user_model

User = get_user_model()


class EditSelectTeam(forms.Form):

    team_choice = forms.ModelChoiceField(widget=forms.RadioSelect, queryset=None)

    def __init__(self, user, *args, **kwargs):
        super(EditSelectTeam, self).__init__(*args, **kwargs)
        self.fields['team_choice'].queryset = Team.objects.all().filter(team_hr_admin = user)

    # def team_select(self):
    #    data = self.cleaned_data['team_choice']
    #    return data

website/views.py
import json
from math import *
import math
import random
import itertools as it
import numpy as np
from scipy.stats.stats import pearsonr
from collections import Counter
from statistics import mode
from django.shortcuts import render, render_to_response, get_object_or_404
from django.views.generic import TemplateView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Project, Team
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from registration.views import MyUser
from .forms import EditSelectTeam
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import EmailMessage
from registration.models import MyUser
from django.template.loader import render_to_string
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from survey.models import Question,Answer,Survey
from survey.models.response import Response
from rest_framework.views import APIView
from rest_framework.response import Response
from survey.models.response import Response as ResponseModel
from .serializers import MyUserSerializer, ProjectSerializer, TeamSerializer
from rest_framework.renderers import TemplateHTMLRenderer
from django.template.defaulttags import register

class HomePage(TemplateView):
    template_name= 'index.html'

class PricingPage(TemplateView):
    template_name="pricing.html"

class LinkTeam(generic.ListView):
    template_name = 'link_project.html'

    def get_queryset(self):
        #import pdb; pdb.set_trace()
        #team2 = Team.objects.all().filter(team_hr_admin = self.request.user)
        queryset = Team.objects.filter(team_hr_admin=self.request.user)
        return queryset


def TeamSelect(request, pk1=None):
    #import pdb; pdb.set_trace()
    if request.method == "POST":
        select_form = EditSelectTeam(request.user, request.POST)
        if select_form.is_valid():
            data = select_form.cleaned_data['team_choice']
            obj2 = Project.objects.filter(project_hr_admin=request.user)
            obj3 = obj2.latest('id')
            if obj3.team_id == None:
                obj3.team_id = data
                obj3.save()
                obj4 = obj3.team_id
                obj5 = obj4.members.all()

                for i in obj5:
                    current_site = get_current_site(request)
                    message = render_to_string('acc_join_email.html', {
                        'user': i.first_name,
                        'domain':current_site.domain,
                        })
                    mail_subject = 'You have been invited to SoftScores.com please LogIn to get access to the app'
                    to_email = i.email
                    email = EmailMessage(mail_subject, message, to=[to_email])
                    email.send()
                messages.success(request, 'test')
                return HttpResponseRedirect(reverse('website:ProjectDetails', kwargs={'pk1':obj3.id}))
            else:
                print('this project has already a team')
        else:
            print('Non Valid form')

    else:
        #import pdb; pdb.set_trace()
        select_form = EditSelectTeam(request.user)
    return render(request,'link_project.html',
                            {'select_form':select_form })

class HRIndex(generic.ListView):
    #import pdb; pdb.set_trace()
    template_name = "HR_index.html"
    model = Project


    def get_queryset(self):
        return Project.objects.filter(project_hr_admin_id = self.request.user).order_by('-created_at')



    def get_context_data(self, **kwargs):
        #import pdb; pdb.set_trace()
        context = super(HRIndex,self).get_context_data(**kwargs)
        status_dict = {}
        for project in Project.objects.filter(project_hr_admin_id = self.request.user):
            proj_team_id = project.team_id
            proj_memb = proj_team_id.members.all()
            open_close = 1
            for memb in proj_memb:
                if not list(memb.response_set.all()):
                    status = False
                else:
                    status = True
                open_close = open_close*status
            status_dict.update({project.id:open_close})

        context['status_dict'] = status_dict
        return context




class CandidateIndex(TemplateView):
    #import pdb; pdb.set_trace()
    template_name = "candidate_index.html"

class EmployeeIndex(TemplateView):
    #import pdb; pdb.set_trace()
    template_name = "employee_index.html"

    def get_object(self, queryset=None):
        return get_object_or_404(Project,id=self.kwargs['pk2'])

    def get_context_data(self, **kwargs):
        context = super(EmployeeIndex, self).get_context_data(**kwargs)
        surveys = Survey.objects.filter(is_published=True)
        user_response_count  = MyUser.objects.get(id = self.kwargs['pk2']).response_set.count()
        #current_user = MyUser.objects.get(id = )
        if not self.request.user.is_authenticated():
            surveys = surveys.filter(need_logged_user=False)
        context['surveys'] = surveys
        context['user_response_count'] = user_response_count
        return context

class ProjectCreate(LoginRequiredMixin, CreateView):
    model = Project
    fields = ['name']
    template_name = 'project_form.html'

    def form_valid(self, form):
        form.instance.project_hr_admin = self.request.user
        return super(ProjectCreate, self).form_valid(form)

class ProjectDetailView(LoginRequiredMixin, generic.DetailView):
    #import pdb; pdb.set_trace()
    model = Project
    template_name = 'project_details.html'

    def get_object(self, queryset=None):
        return get_object_or_404(Project,id=self.kwargs['pk1'])

    def get_context_data(self, **kwargs):
        context = super(ProjectDetailView, self).get_context_data(**kwargs)
        try:

            team_name = Project.objects.get(id=self.kwargs['pk1']).team_id.members.all()
            score = get_team_cohesivenss_score(self)[0]

            all_user_response = 1
            for i in Project.objects.get(id=self.kwargs['pk1']).team_id.members.all():
                if i.response_set.all().count() == 0:
                    all_user_response = all_user_response * 0
                else:
                    all_user_response = all_user_response * 1

            context['team_name'] = team_name
            context['score'] = score
            context['all_user_response'] = all_user_response
        except AttributeError:
            pass
        return context

class EmployeeDetailView(LoginRequiredMixin, generic.DetailView):
    #import pdb; pdb.set_trace()
    model = MyUser
    template_name = 'employee_details.html'


    def get_object(self, queryset=None):
        return get_object_or_404(MyUser, pk=self.kwargs['pk2'], members__project=self.kwargs['pk1'])

    def get_context_data(self, **kwargs):
        context = super(EmployeeDetailView, self).get_context_data(**kwargs)
        employee_name = MyUser.objects.get(id=self.kwargs['pk2'])
        team_list = Project.objects.get(id=self.kwargs['pk1']).team_id.members.all()
        team_list_pop = Project.objects.get(id=self.kwargs['pk1']).team_id.members.all().exclude(id=self.kwargs['pk2'])

        context={
            'employee_name' : employee_name,
            'team_list' : team_list,
            'team_list_pop' : team_list_pop,
        }
        return context

class CandidateDetailView(LoginRequiredMixin, generic.DetailView):
    #import pdb; pdb.set_trace()
    model = MyUser
    template_name = 'applicant_details.html'

    def get_object(self, queryset=None):
        return get_object_or_404(MyUser, pk=self.kwargs['pk2'])

    def get_context_data(self, **kwargs):
        context = super(CandidateDetailView, self).get_context_data(**kwargs)
        team_score = get_team_cohesivenss_score(self)[0]
        applicant_score = get_applicant_cohesivenss_score(self)[0][0]
        employee_name = MyUser.objects.get(id=self.kwargs['pk2'])
        diff_score = get_applicant_cohesivenss_score(self)[0][0] - get_team_cohesivenss_score(self)[0]
        team_list_pop = Project.objects.get(id=self.kwargs['pk1']).team_id.members.all().exclude(id=self.kwargs['pk2'])
        context['team_score'] = team_score
        context['applicant_score'] = applicant_score
        context['diff_score'] = diff_score
        context['team_list_pop'] = team_list_pop
        context['employee_name'] = employee_name

        return context



class TeamCreate(CreateView):

    model = Team
    fields = ['team_name']
    template_name = 'team_form.html'

    def form_valid(self, form):
        #import pdb; pdb.set_trace()
        valid = super(TeamCreate, self).form_valid(form)
        form.instance.team_hr_admin = self.request.user
        obj = form.save()
        #SELECT * FROM project WHERE user = 'current_user' AND team_id = NULL
        obj2 = Project.objects.get(project_hr_admin=self.request.user, team_id=None)
        obj2.team_id = obj
        obj2.save()
        return valid
        return super(TeamCreate, self).form_valid(form)

    def get_success_url(self):
        #import pdb; pdb.set_trace()
        project = Project.objects.get(team_id=None, project_hr_admin=self.request.user)
        return project.get_absolute_url()

class EmployeeChartData(APIView):
    #import pdb; pdb.set_trace()
    #queryset = MyUser.objects.all()
    #serializer_class = MyUserSerializer
    #permission_classes = []
    http_method_names = ['get',]

    #authentication_classes = []
    #permission_classes = []
    #serializer_class = MyUserSerializer

    def get_serializer_class(self):
        return self.serializer_class



    def get(self, request, format=None, *args, **kwargs):
        current_project = get_current_team(self)
        #info Process
        info_array2 = get_employee_info_array(self)

website/views/payment_views.py
from Authentication_project import settings
from django.views.generic import TemplateView
from django.shortcuts import redirect
import stripe
from django.contrib import messages
stripe.api_key = settings.STRIPE_SECRET_KEY


class payment_form(TemplateView):
    template_name = "transaction.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['stripe_key'] = settings.STRIPE_PUBLIC_KEY
        return context


def checkout(request):
    import pdb; pdb.set_trace()
    if request.method == "POST":
        token = request.POST.get("stripeToken")
        price = 6000
        volume = int(request.POST.get("credit"))
        final_price = price * volume
    try:
        charge = stripe.Charge.create(
            amount=final_price,
            currency="usd",
            source=token,
            description="SoftScores Team Assessment",
            receipt_email=request.user.email,
        )

        user = request.user
        user.credit = user.credit + volume
        user.save()
    except stripe.error.CardError as e:

        # Since it's a decline, stripe.error.CardError will be caught
        body = e.json_body
        err = body['error']
        messages.error(request, "There was a problem processing your payment: %s" % err['code'])
        return redirect('website:payment')
    else:

        return redirect('website:create_project')

website/views/website_front.py
from django.views.generic import TemplateView


class HomePage(TemplateView):
    template_name = 'index.html'


class PricingPage(TemplateView):
    template_name = "pricing.html"


# 2

website/templates/projectdetailtemp/noteamcreated.html
{% load static %}
<div class="invite-team">
  <div class="jumbotron greenback">
    <div class="container">
      <div class="row justify-content-center">
        <div class="jumbo-text">
          <h7>Your project has been created, It is time to link a team or create a new for your project</h7>
        </div>
      </div>
      <div class="row justify-content-center">
        <div class="jumbo-button">
          <a href="{% url 'website:team_select' pk1=project.id %}" class="btn btn-secondary" role="button"><i class="fas fa-link"></i>   Link an existing team</a>
          <a href="{% url 'website:add_team' pk1=project.id %}" class="btn btn-success" role="button"><i class="fas fa-plus-circle"></i>   Create a new team</a>
        </div>
      </div>
    </div>



  </div>
</div>

website/templates/projectdetailtemp/other.html
{% load static %}
<div class="container">
  <div class="row justify-content-between">
    <div class="col">
      <h3>{{project.team_id}}</h3>
    </div>
    <div class="col-3">
        {% for member in project.team_id.members.all %}
      {% if member.is_manager and member.response_set.count == 0 %}
      <a class="btn btn-danger btn-xs btn-block btn-survey" href="{% url 'website:employee_index' pk2=member.id %}"><i class="fas fa-arrow-right arrow-left"></i>    Take the survey    <i class="fas fa-arrow-left arrow-right"></i></a>
        <!--<a href="{% url 'website:recruitment' pk1=project.id %}" class="btn btn-success btn-text float-right" role="button"><i class="fas fa-link"></i>   Recruitment process page</a>-->
      {% else %}

        <!--<a href="#" class="btn redback btn-text float-right" role="button"><i class="fas fa-link"></i>   Waiting for team members to start recruitment</a> -->
    {% endif %}
    {% endfor %}
    </div>
  </div>
</div>

<div class="team-container">
  <div class="row">
  {% for member in project.team_id.members.all %}
    <div class="col">
      <div class="bord">
          <div class="profil_pic">
          {% if member.first_name == None or member.last_name == None%}
            <img src="{% static "images/people-bw.png" %}" alt="" style="height:100px">
          {% else %}
              {% if member.gender == 'M' %}
                <img src="{% static "images/men-color.png" %}" alt="" style="height:100px">
              {% else %}
                <img src="{% static "images/women-color.png" %}" alt="" style="height:100px">
              {% endif %}
          {% endif %}
        </div>
          <div class="OuterContent">
              <div class="InnerContent">
                {% if member.first_name == None or member.last_name == None%}
                <div class="name_content">
                    <div class="email">
                       {{ member.email }}
                    </div>
                    <div class="register">
                      Not Registred yet
                    </div>
                </div>
                {% else %}
                <div class="name_content">
                    {{ member.first_name}} {{ member.last_name}}
                </div>
                  <div class="survey-taken register">
                    {% if member.response_set.count > 0 %}
                        Survey has been taken - <i class="fas fa-thumbs-up" style="color:green"></i>
                        {% if all_user_response == 1 %}
                        <div class="result-link">
                          <i class="fas fa-id-card"></i><a href="{% url 'website:EmployeDetails' pk1=project.id pk2=member.id %}"> Show Results</a>
                        </div>
                        {% endif%}
                    {% else %}
                        Survey has not been taken yet - <i class="fas fa-thumbs-down" aria-hidden="true" style="color:red"></i>
                   {% endif %}
                  </div>
                {% endif %}
              </div>
          </div>
      </div>
    </div>
  {% endfor %}
  </div>
</div>

website/templates/projectdetailtemp/teamnomember.html
{% load static %}
<div class="invite-teammembers">
  <div class="jumbotron greenback">
    <div class="jumbo-text">
      <div class="container">
        <div class="row justify-content-center">
          <h7>The team {{ project.team_id }} has beed created, we now need to add TeamMembers</h7>
        </div>
        <div class="row">
          <div class="jumbo-button2 justify-content-center">
            <a href="{% url 'registration:team_register3' pk1=project.id %}" class="btn btn-success" role="button"><span class="glyphicon glyphicon-plus"></span>   Add Team Members</a>
          </div>
        </div>

      </div>
</div>
</div>