Authentication_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from website.views.website_front import *

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^registration/', include('registration.urls')),
    url(r'^website/', include('website.urls')),
    url(r'^survey/', include('SurveyApp.urls')),
    url(r'^$', HomePage.as_view(), name='index'),
    url(r'^pricing', PricingPage.as_view(), name='pricing'),
]

registration/urls.py
from django.conf.urls import url
from registration import views

app_name = 'registration'
urlpatterns = [
    url(r'^hr_register/$', views.registerHR, name='hr_register'),
    url(r'^manager_register/$', views.registerManager, name="manager_register"),
    url(r'^auth_HRlogin/$', views.HR_login, name='HRlogin'),
    url(r'^update/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.CandidateSignIn, name='CandidateSignIn'),
    url(r'^auth_logout/$', views.user_logout, name='logout'),
    url(r'^project/(?P<pk1>[0-9]+)/auth_team_register3/$',
        views.TeamRegister2, name='team_register3'),
    url(r'^project/(?P<pk1>[0-9]+)/auth_applicant_register3/$',
        views.applicantregister2, name='applicant_register3'),

]

website/urls.py
from django.conf.urls import url, include
from website.views import *
from website import views

app_name = 'website'
urlpatterns = [
    url(r'^hr_index/$', HRIndex.as_view(), name='hr_index'),
    url(r'^create_project/$', CreateProject.as_view(), name='create_project'),
    url(r'^candidate_index/$', CandidateIndex.as_view(),name='candidate_index'),
    url(r'^employee_index/(?P<pk2>[0-9]+)/$', EmployeeIndex.as_view(),name='employee_index'),
    url(r'^addproject/$', ProjectCreate.as_view(), name='add_project'),
    url(r'^project/(?P<pk1>[0-9]+)/create_team/$', CreateTeam.as_view(), name='create_team'),
    url(r'^project/(?P<pk1>[0-9]+)/addteam/$', TeamCreate.as_view(), name='add_team'),
    #url(r'^project/(?P<pk1>[0-9]+)/linkteam2/$', TeamSelect, name='team_select'),
    url(r'^project/(?P<pk1>[0-9]+)/$',ProjectDetailView.as_view(), name='ProjectDetails'),
    url(r'^project/(?P<pk1>[0-9]+)/api/chart/data2/$',TeamChartData.as_view(), name='TeamChartData'),
    url(r'^project/employee/(?P<pk1>[0-9]+)/(?P<pk2>[0-9]+)/$',EmployeeDetailView.as_view(), name='EmployeDetails'),
    url(r'^project/applicant/(?P<pk1>[0-9]+)/(?P<pk2>[0-9]+)/$',CandidateDetailView.as_view(), name='CandidateDetails'),
    url(r'^project/employee/(?P<pk1>[0-9]+)/(?P<pk2>[0-9]+)/api/chart/data/$',EmployeeChartData.as_view(), name='EmployeeChartData'),
    url(r'^project/applicant/(?P<pk1>[0-9]+)/(?P<pk2>[0-9]+)/api/chart/data3/$',applicantChartData.as_view(), name='CandidateChartData'),
    url(r'^project/(?P<pk1>[0-9]+)/recruitment/$', RecruitmentPage.as_view(), name='recruitment'),
    url(r'^payment_form/$', payment_form.as_view(), name='payment'),
    url(r'^checkout/$', views.checkout, name="checkout_page"),
]

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title>SoftScore - Team Recruitment Analytics</title>
    <!-- CSS-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static '/css/master.css' %}">
    <link href="{% static 'css/widgets.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/index.css' %}" rel="stylesheet">
    {% block extracss %}{% endblock %}

    <link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.ico'%}"/>
    <link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.ico'%}"/>

    <!-- Fonts-->
    <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">

    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>

    <!-- Plugin CSS -->
    <link href="{% static "vendor/magnific-popup/magnific-popup.css" %}" rel="stylesheet">

    <!-- Java Script-->
    <script src="https://code.jquery.com/jquery-3.2.1.js" integrity="sha256-DZAnKJ/6XZ9si04Hgrsxu/8s717jcIzLy3oi35EouyE=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.13.0/umd/popper.min.js" integrity="sha256-pS96pU17yq+gVu4KBQJi38VpSuKN7otMrDQprzf/DWY=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.13.0/umd/popper-utils.min.js" integrity="sha256-8h5msWnq3iF3K5ntJlLObPIzG7+48GOyk32q0CJdRGI=" crossorigin="anonymous"></script>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.29.4/js/jquery.tablesorter.js" integrity="sha256-9kqrSdgKTE8E6A94yfeahUKKP1bwZNrh4HO9H6gCz/A=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.29.4/js/jquery.tablesorter.widgets.js" integrity="sha256-ulL5Ln7fwxHfXScZcGp9l0O+BiMwMBOsc5yYVdD7qdk=" crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>


  </head>
  <body id="page-top">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
      <div class="container">
            <a class="navbar-brand js-scroll-trigger" href="{% url 'index' %}"><img src="{% static 'images/logo.png' %}" alt="logo"></a>

        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="#about">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="#services">Services</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="#contact">Contact</a>
            </li>
            {% if user.is_authenticated  %}
              {% if user.is_employee == False and user.is_candidate == False %}
            <li class="nav-item green-menu"><a class="nav-link js-scroll-trigger" href="{% url 'website:hr_index' %}"><span class="fa fa-user-circle"></span> {{ request.user.first_name }} {{ request.user.last_name }}</a></li>
              {% endif %}
            <li class="nav-item green-menu"><a class="nav-link js-scroll-trigger" href="{% url 'registration:logout'%}"><span class="fas fa-sign-out-alt"></span> Log Out</a></li>

            {% else %}
            <li class="nav-item green-menu"><a class="nav-link js-scroll-trigger signin" href="{% url 'registration:manager_register' %}"><span class="fas fa-sign-in-alt"></span> SignIn</a></li>
            <li class="nav-item green-menu"><a class="nav-link js-scroll-trigger login" href="{% url 'registration:HRlogin' %}"><span class="fas fa-sign-in-alt"></span> Login</a></li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>

    <!-- Message -->
      {% if messages%}
      <div class="row">
        <div class="col-xl-offset-12">

              {% for message in messages%}
                <p{% if message.tags == "success" %} class="alert alert-success"{% endif %}>{{ message }}</p>
              {% endfor %}

        </div>
      </div>
      {% endif %}
    <!-- End Message -->

    {% block body %}
    {% endblock %}

    {% block extrajs %}{% endblock %}
  </body>
</html>

templates/index2.html
{% extends 'base.html' %}

{% block body %}
<div class="bg">
  <div class="container">
    <div class="jumbotron">
      <h1>Welcome to SoftScores.com</h1>
      <h2>Team analytics platfom</h2>
    </div>

  </div>

</div>
<div class="jumbotron">
  <h1>Welcome to SoftScores.com</h1>
  <h2>Team analytics platfom</h2>
</div>
<div class="jumbotron">
  <h1>Welcome to SoftScores.com</h1>
  <h2>Team analytics platfom</h2>
</div>
<div class="jumbotron">
  <h1>Welcome to SoftScores.com</h1>
  <h2>Team analytics platfom</h2>
</div>

{% endblock %}

templates/pricing.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block extracss %}
<link href="{% static 'css/pricing/reset.css' %}" rel="stylesheet" type="text/css">
<link href="{% static 'css/pricing/style.css' %}" rel="stylesheet" type="text/css">
{% endblock %}


{% block body %}
<div class="pricing-container">
  <header class="cd-header">
    <h1>Pricing Tables</h1>
  </header>

  <div class="cd-pricing-container cd-full-width cd-secondary-theme">
		<div class="cd-pricing-switcher">
			<p class="fieldset">
				<input type="radio" name="duration" value="monthly" id="monthly" checked>
				<label for="monthly">Monthly</label>
				<input type="radio" name="duration" value="yearly" id="yearly">
				<label for="yearly">Yearly</label>
				<span class="cd-switch"></span>
			</p>
		</div> <!-- .cd-pricing-switcher -->
<div class="container">
  <ul class="cd-pricing-list cd-bounce-invert">
    <li>
      <ul class="cd-pricing-wrapper">
        <li data-type="monthly" class="is-visible">
          <header class="cd-pricing-header">
            <h2>Basic</h2>

            <div class="cd-price">
              <span class="cd-currency">$</span>
              <span class="cd-value">260</span>
              <span class="cd-duration">mo</span>
            </div>
          </header> <!-- .cd-pricing-header -->

          <div class="cd-pricing-body">
            <ul class="cd-pricing-features">
              <li><em>1</em> User</li>
              <li><em>3</em> Projects per month</li>
              <li><em>Limited</em> Support</li>
            </ul>
          </div> <!-- .cd-pricing-body -->

          <footer class="cd-pricing-footer">
            <a class="cd-select" href="#">Select</a>
          </footer> <!-- .cd-pricing-footer -->
        </li>

        <li data-type="yearly" class="is-hidden">
          <header class="cd-pricing-header">
            <h2>Basic</h2>

            <div class="cd-price">
              <span class="cd-currency">$</span>
              <span class="cd-value">2900</span>
              <span class="cd-duration">yr</span>
            </div>
          </header> <!-- .cd-pricing-header -->

          <div class="cd-pricing-body">
            <ul class="cd-pricing-features">
              <li><em>1</em> User</li>
              <li><em>3</em> Projects per month</li>
              <li><em>Limited</em> Support</li>
            </ul>
          </div> <!-- .cd-pricing-body -->

          <footer class="cd-pricing-footer">
            <a class="cd-select" href="#">Select</a>
          </footer> <!-- .cd-pricing-footer -->
        </li>
      </ul> <!-- .cd-pricing-wrapper -->
    </li>

    <li class="cd-popular">
      <ul class="cd-pricing-wrapper">
        <li data-type="monthly" class="is-visible">
          <header class="cd-pricing-header">
            <h2>Standart</h2>

            <div class="cd-price">
              <span class="cd-currency">$</span>
              <span class="cd-value">450</span>
              <span class="cd-duration">mo</span>
            </div>
          </header> <!-- .cd-pricing-header -->

          <div class="cd-pricing-body">
            <ul class="cd-pricing-features">
              <li><em><5</em> Users</li>
              <li><em>10</em> Projects per month</li>
              <li><em>Complete</em> Report</li>
              <li><em>Unlimited</em> Support</li>
            </ul>
          </div> <!-- .cd-pricing-body -->

          <footer class="cd-pricing-footer">
            <a class="cd-select" href="#">Select</a>
          </footer> <!-- .cd-pricing-footer -->
        </li>

        <li data-type="yearly" class="is-hidden">
          <header class="cd-pricing-header">
            <h2>Popular</h2>

            <div class="cd-price">
              <span class="cd-currency">$</span>
              <span class="cd-value">4900</span>
              <span class="cd-duration">yr</span>
            </div>
          </header> <!-- .cd-pricing-header -->

          <div class="cd-pricing-body">
            <ul class="cd-pricing-features">
              <li><em><5</em> Users</li>
              <li><em>10</em> Projects per month</li>
              <li><em>Complete</em> Report</li>
              <li><em>Unlimited</em> Support</li>
            </ul>
          </div> <!-- .cd-pricing-body -->

          <footer class="cd-pricing-footer">
            <a class="cd-select" href="#">Select</a>
          </footer> <!-- .cd-pricing-footer -->
        </li>
      </ul>
    </li> <!-- .cd-pricing-wrapper -->

    <li>
      <ul class="cd-pricing-wrapper">
        <li data-type="monthly" class="is-visible">
          <header class="cd-pricing-header">
            <h2>Premium</h2>

            <div class="cd-price">
              <span class="cd-currency">$</span>
              <span class="cd-value">530</span>
              <span class="cd-duration">mo</span>
            </div>
          </header> <!-- .cd-pricing-header -->

          <div class="cd-pricing-body">
            <ul class="cd-pricing-features">
              <li><em><10</em> Users</li>
              <li><em>Unlimited</em> Projects</li>
              <li><em>Complete</em> Report</li>
              <li><em>Unlimited</em> Support</li>
              <li><em>Complete</em> education</li>
            </ul>
          </div> <!-- .cd-pricing-body -->

          <footer class="cd-pricing-footer">
            <a class="cd-select" href="#">Select</a>
          </footer> <!-- .cd-pricing-footer -->
        </li>

        <li data-type="yearly" class="is-hidden">
          <header class="cd-pricing-header">
            <h2>Premier</h2>

            <div class="cd-price">
              <span class="cd-currency">$</span>
              <span class="cd-value">5900</span>
              <span class="cd-duration">yr</span>
            </div>
          </header> <!-- .cd-pricing-header -->

          <div class="cd-pricing-body">
            <ul class="cd-pricing-features">
              <li><em><10</em> Users</li>
              <li><em>Unlimited</em> Projects</li>
              <li><em>10</em> Domains</li>
              <li><em>Unlimited</em> Bandwidth</li>
              <li><em>24/7</em> Support</li>
              <li><em>Complete</em> education</li>  
            </ul>
          </div> <!-- .cd-pricing-body -->

          <footer class="cd-pricing-footer">
            <a class="cd-select" href="#">Select</a>
          </footer> <!-- .cd-pricing-footer -->
        </li>
      </ul> <!-- .cd-pricing-wrapper -->
    </li>
  </ul> <!-- .cd-pricing-list -->
</div>

	</div> <!-- .cd-pricing-container -->

</div>

{% block extrajs %}
<script src={% static "js/pricing/modernizr.js" %}></script>
<script src={% static "js/pricing/main.js" %}></script> <!-- Resource jQuery -->
{% endblock %}



{% endblock %}