Authentication_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from website.views.website_front import *

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^registration/', include('registration.urls')),
    url(r'^website/', include('website.urls')),
    url(r'^survey/', include('SurveyApp.urls')),
    url(r'^$', HomePage.as_view(), name='index'),
    url(r'^pricing', PricingPage.as_view(), name='pricing'),
]

registration/urls.py
from django.conf.urls import url
from registration import views

app_name = 'registration'
urlpatterns = [
    url(r'^hr_register/$', views.registerHR, name='hr_register'),
    url(r'^manager_register/$', views.registerManager, name="manager_register"),
    url(r'^auth_HRlogin/$', views.HR_login, name='HRlogin'),
    url(r'^update/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.CandidateSignIn, name='CandidateSignIn'),
    url(r'^auth_logout/$', views.user_logout, name='logout'),
    url(r'^project/(?P<pk1>[0-9]+)/auth_team_register3/$',
        views.TeamRegister2, name='team_register3'),
    url(r'^project/(?P<pk1>[0-9]+)/auth_applicant_register3/$',
        views.applicantregister2, name='applicant_register3'),

]

website/urls.py
from django.conf.urls import url, include
from website.views import *
from website import views

app_name = 'website'
urlpatterns = [
    url(r'^hr_index/$', HRIndex.as_view(), name='hr_index'),
    url(r'^create_project/$', CreateProject.as_view(), name='create_project'),
    url(r'^candidate_index/$', CandidateIndex.as_view(),name='candidate_index'),
    url(r'^employee_index/(?P<pk2>[0-9]+)/$', EmployeeIndex.as_view(),name='employee_index'),
    url(r'^addproject/$', ProjectCreate.as_view(), name='add_project'),
    url(r'^project/(?P<pk1>[0-9]+)/create_team/$', CreateTeam.as_view(), name='create_team'),
    url(r'^project/(?P<pk1>[0-9]+)/addteam/$', TeamCreate.as_view(), name='add_team'),
    #url(r'^project/(?P<pk1>[0-9]+)/linkteam2/$', TeamSelect, name='team_select'),
    url(r'^project/(?P<pk1>[0-9]+)/$',ProjectDetailView.as_view(), name='ProjectDetails'),
    url(r'^project/(?P<pk1>[0-9]+)/api/chart/data2/$',TeamChartData.as_view(), name='TeamChartData'),
    url(r'^project/employee/(?P<pk1>[0-9]+)/(?P<pk2>[0-9]+)/$',EmployeeDetailView.as_view(), name='EmployeDetails'),
    url(r'^project/applicant/(?P<pk1>[0-9]+)/(?P<pk2>[0-9]+)/$',CandidateDetailView.as_view(), name='CandidateDetails'),
    url(r'^project/employee/(?P<pk1>[0-9]+)/(?P<pk2>[0-9]+)/api/chart/data/$',EmployeeChartData.as_view(), name='EmployeeChartData'),
    url(r'^project/applicant/(?P<pk1>[0-9]+)/(?P<pk2>[0-9]+)/api/chart/data3/$',applicantChartData.as_view(), name='CandidateChartData'),
    url(r'^project/(?P<pk1>[0-9]+)/recruitment/$', RecruitmentPage.as_view(), name='recruitment'),
    url(r'^payment_form/$', payment_form.as_view(), name='payment'),
    url(r'^checkout/$', views.checkout, name="checkout_page"),
]

website/forms.py
from django import forms
from django.contrib.auth.models import User
from registration.models import MyUser
from .models import Team
from django.contrib.auth import get_user_model

User = get_user_model()


class EditSelectTeam(forms.Form):

    team_choice = forms.ModelChoiceField(widget=forms.RadioSelect, queryset=None)

    def __init__(self, user, *args, **kwargs):
        super(EditSelectTeam, self).__init__(*args, **kwargs)
        self.fields['team_choice'].queryset = Team.objects.all().filter(team_hr_admin = user)

    # def team_select(self):
    #    data = self.cleaned_data['team_choice']
    #    return data

website/views.py
import json
from math import *
import math
import random
import itertools as it
import numpy as np
from scipy.stats.stats import pearsonr
from collections import Counter
from statistics import mode
from django.shortcuts import render, render_to_response, get_object_or_404
from django.views.generic import TemplateView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Project, Team
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from registration.views import MyUser
from .forms import EditSelectTeam
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import EmailMessage
from registration.models import MyUser
from django.template.loader import render_to_string
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from survey.models import Question,Answer,Survey
from survey.models.response import Response
from rest_framework.views import APIView
from rest_framework.response import Response
from survey.models.response import Response as ResponseModel
from .serializers import MyUserSerializer, ProjectSerializer, TeamSerializer
from rest_framework.renderers import TemplateHTMLRenderer
from django.template.defaulttags import register

class HomePage(TemplateView):
    template_name= 'index.html'

class PricingPage(TemplateView):
    template_name="pricing.html"

class LinkTeam(generic.ListView):
    template_name = 'link_project.html'

    def get_queryset(self):
        #import pdb; pdb.set_trace()
        #team2 = Team.objects.all().filter(team_hr_admin = self.request.user)
        queryset = Team.objects.filter(team_hr_admin=self.request.user)
        return queryset


def TeamSelect(request, pk1=None):
    #import pdb; pdb.set_trace()
    if request.method == "POST":
        select_form = EditSelectTeam(request.user, request.POST)
        if select_form.is_valid():
            data = select_form.cleaned_data['team_choice']
            obj2 = Project.objects.filter(project_hr_admin=request.user)
            obj3 = obj2.latest('id')
            if obj3.team_id == None:
                obj3.team_id = data
                obj3.save()
                obj4 = obj3.team_id
                obj5 = obj4.members.all()

                for i in obj5:
                    current_site = get_current_site(request)
                    message = render_to_string('acc_join_email.html', {
                        'user': i.first_name,
                        'domain':current_site.domain,
                        })
                    mail_subject = 'You have been invited to SoftScores.com please LogIn to get access to the app'
                    to_email = i.email
                    email = EmailMessage(mail_subject, message, to=[to_email])
                    email.send()
                messages.success(request, 'test')
                return HttpResponseRedirect(reverse('website:ProjectDetails', kwargs={'pk1':obj3.id}))
            else:
                print('this project has already a team')
        else:
            print('Non Valid form')

    else:
        #import pdb; pdb.set_trace()
        select_form = EditSelectTeam(request.user)
    return render(request,'link_project.html',
                            {'select_form':select_form })

class HRIndex(generic.ListView):
    #import pdb; pdb.set_trace()
    template_name = "HR_index.html"
    model = Project


    def get_queryset(self):
        return Project.objects.filter(project_hr_admin_id = self.request.user).order_by('-created_at')



    def get_context_data(self, **kwargs):
        #import pdb; pdb.set_trace()
        context = super(HRIndex,self).get_context_data(**kwargs)
        status_dict = {}
        for project in Project.objects.filter(project_hr_admin_id = self.request.user):
            proj_team_id = project.team_id
            proj_memb = proj_team_id.members.all()
            open_close = 1
            for memb in proj_memb:
                if not list(memb.response_set.all()):
                    status = False
                else:
                    status = True
                open_close = open_close*status
            status_dict.update({project.id:open_close})

        context['status_dict'] = status_dict
        return context




class CandidateIndex(TemplateView):
    #import pdb; pdb.set_trace()
    template_name = "candidate_index.html"

class EmployeeIndex(TemplateView):
    #import pdb; pdb.set_trace()
    template_name = "employee_index.html"

    def get_object(self, queryset=None):
        return get_object_or_404(Project,id=self.kwargs['pk2'])

    def get_context_data(self, **kwargs):
        context = super(EmployeeIndex, self).get_context_data(**kwargs)
        surveys = Survey.objects.filter(is_published=True)
        user_response_count  = MyUser.objects.get(id = self.kwargs['pk2']).response_set.count()
        #current_user = MyUser.objects.get(id = )
        if not self.request.user.is_authenticated():
            surveys = surveys.filter(need_logged_user=False)
        context['surveys'] = surveys
        context['user_response_count'] = user_response_count
        return context

class ProjectCreate(LoginRequiredMixin, CreateView):
    model = Project
    fields = ['name']
    template_name = 'project_form.html'

    def form_valid(self, form):
        form.instance.project_hr_admin = self.request.user
        return super(ProjectCreate, self).form_valid(form)

class ProjectDetailView(LoginRequiredMixin, generic.DetailView):
    #import pdb; pdb.set_trace()
    model = Project
    template_name = 'project_details.html'

    def get_object(self, queryset=None):
        return get_object_or_404(Project,id=self.kwargs['pk1'])

    def get_context_data(self, **kwargs):
        context = super(ProjectDetailView, self).get_context_data(**kwargs)
        try:

            team_name = Project.objects.get(id=self.kwargs['pk1']).team_id.members.all()
            score = get_team_cohesivenss_score(self)[0]

            all_user_response = 1
            for i in Project.objects.get(id=self.kwargs['pk1']).team_id.members.all():
                if i.response_set.all().count() == 0:
                    all_user_response = all_user_response * 0
                else:
                    all_user_response = all_user_response * 1

            context['team_name'] = team_name
            context['score'] = score
            context['all_user_response'] = all_user_response
        except AttributeError:
            pass
        return context

class EmployeeDetailView(LoginRequiredMixin, generic.DetailView):
    #import pdb; pdb.set_trace()
    model = MyUser
    template_name = 'employee_details.html'


    def get_object(self, queryset=None):
        return get_object_or_404(MyUser, pk=self.kwargs['pk2'], members__project=self.kwargs['pk1'])

    def get_context_data(self, **kwargs):
        context = super(EmployeeDetailView, self).get_context_data(**kwargs)
        employee_name = MyUser.objects.get(id=self.kwargs['pk2'])
        team_list = Project.objects.get(id=self.kwargs['pk1']).team_id.members.all()
        team_list_pop = Project.objects.get(id=self.kwargs['pk1']).team_id.members.all().exclude(id=self.kwargs['pk2'])

        context={
            'employee_name' : employee_name,
            'team_list' : team_list,
            'team_list_pop' : team_list_pop,
        }
        return context

class CandidateDetailView(LoginRequiredMixin, generic.DetailView):
    #import pdb; pdb.set_trace()
    model = MyUser
    template_name = 'applicant_details.html'

    def get_object(self, queryset=None):
        return get_object_or_404(MyUser, pk=self.kwargs['pk2'])

    def get_context_data(self, **kwargs):
        context = super(CandidateDetailView, self).get_context_data(**kwargs)
        team_score = get_team_cohesivenss_score(self)[0]
        applicant_score = get_applicant_cohesivenss_score(self)[0][0]
        employee_name = MyUser.objects.get(id=self.kwargs['pk2'])
        diff_score = get_applicant_cohesivenss_score(self)[0][0] - get_team_cohesivenss_score(self)[0]
        team_list_pop = Project.objects.get(id=self.kwargs['pk1']).team_id.members.all().exclude(id=self.kwargs['pk2'])
        context['team_score'] = team_score
        context['applicant_score'] = applicant_score
        context['diff_score'] = diff_score
        context['team_list_pop'] = team_list_pop
        context['employee_name'] = employee_name

        return context



class TeamCreate(CreateView):

    model = Team
    fields = ['team_name']
    template_name = 'team_form.html'

    def form_valid(self, form):
        #import pdb; pdb.set_trace()
        valid = super(TeamCreate, self).form_valid(form)
        form.instance.team_hr_admin = self.request.user
        obj = form.save()
        #SELECT * FROM project WHERE user = 'current_user' AND team_id = NULL
        obj2 = Project.objects.get(project_hr_admin=self.request.user, team_id=None)
        obj2.team_id = obj
        obj2.save()
        return valid
        return super(TeamCreate, self).form_valid(form)

    def get_success_url(self):
        #import pdb; pdb.set_trace()
        project = Project.objects.get(team_id=None, project_hr_admin=self.request.user)
        return project.get_absolute_url()

class EmployeeChartData(APIView):
    #import pdb; pdb.set_trace()
    #queryset = MyUser.objects.all()
    #serializer_class = MyUserSerializer
    #permission_classes = []
    http_method_names = ['get',]

    #authentication_classes = []
    #permission_classes = []
    #serializer_class = MyUserSerializer

    def get_serializer_class(self):
        return self.serializer_class



    def get(self, request, format=None, *args, **kwargs):
        current_project = get_current_team(self)
        #info Process
        info_array2 = get_employee_info_array(self)

website/views/payment_views.py
from Authentication_project import settings
from django.views.generic import TemplateView
from django.shortcuts import redirect
import stripe
from django.contrib import messages
stripe.api_key = settings.STRIPE_SECRET_KEY


class payment_form(TemplateView):
    template_name = "transaction.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['stripe_key'] = settings.STRIPE_PUBLIC_KEY
        return context


def checkout(request):
    import pdb; pdb.set_trace()
    if request.method == "POST":
        token = request.POST.get("stripeToken")
        price = 6000
        volume = int(request.POST.get("credit"))
        final_price = price * volume
    try:
        charge = stripe.Charge.create(
            amount=final_price,
            currency="usd",
            source=token,
            description="SoftScores Team Assessment",
            receipt_email=request.user.email,
        )

        user = request.user
        user.credit = user.credit + volume
        user.save()
    except stripe.error.CardError as e:

        # Since it's a decline, stripe.error.CardError will be caught
        body = e.json_body
        err = body['error']
        messages.error(request, "There was a problem processing your payment: %s" % err['code'])
        return redirect('website:payment')
    else:

        return redirect('website:create_project')

website/views/website_front.py
from django.views.generic import TemplateView


class HomePage(TemplateView):
    template_name = 'index.html'


class PricingPage(TemplateView):
    template_name = "pricing.html"


# 2

website/templates/HR_index.html
{% extends 'base.html' %}
{% load static %}

{% block body %}


{% if messages %}
{% for message in messages %}
<div class="modal fade" id="modal-message" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
{% endfor %}
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <img class="card-img-top" src="{% static "images/welcome-img.png"%}" alt="Card image cap">
      <div class="modal-body">
          <div class="messages">
            {% for message in messages %}
            {% if message.extra_tags == "project" %}
              <h4 class="{{ message.tags }}">{{ message }}</h1>
                <div class="welcome-content">
                    <p>
                      We are glad to know that your team is important to you !
                    </p>
                    <div class="">
                      You just accessed your project list page. Here you will be able to access all your project and create new one.
                    </div>
                    <div class="welcome-arrow">
                      Next step <i class="fas fa-arrow-circle-right"></i> Create your first project</div>
                </div>
              {% endif %}
              {% if message.extra_tags == "team" %}
                <h4 class="{{ message.tags }}">{{ message }}</h1>
                  <div class="welcome-content">
                      <p>
                        It is now your turn to answer our survey !
                      </p>
                      <div class="">
                        When you and your team will be finished answering the survey you will then access your dashboard
                      </div>
                      <div class="welcome-arrow">
                        Next step: <a class="btn btn-danger btn-xs btn-survey" href="{% url 'website:employee_index' pk2=user.id %}"><i class="fas fa-arrow-right arrow-left"></i>Take the survey<i class="fas fa-arrow-left arrow-right"></i></a>
                      </div>
                  </div>
                {% endif %}

            {% endfor %}

          </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary btn-sm" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
{% endif %}

<div class="container hr-index">
  {% if project_list.count < 1 %}
  <div class="row demo-back">
    <div class="col">
      <div class="demoimg">
        <div class="row">
          <div class="col-4 offset-md-1">
            <div class="text-demo">
              <h2>We promised a demo ? </h3>
              <h5>Here it is ....</h5>
            </div>

          </div>
          <div class="col-2 offset-md-3">

            <button type="button" class="btn btn-danger btn-lg" data-toggle="modal" data-target="#test2">
              Watch our demo
            </button>
            <!-- Modal -->
              <div class="modal fade" id="test2" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered video-demo" role="document">
                  <div class="modal-content">
                    <div class="modal-body">
                      <div class="embed-responsive embed-responsive-16by9"><iframe src="https://player.vimeo.com/video/264404960?loop=1&title=0&byline=0&portrait=0" width="1200" height="675" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>">
                        </div>
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                      <button type="button" class="btn btn-secondary" data-dismiss="modal">Create your first project</button>

                    </div>
                  </div>
                </div>
              </div>
          </div>
        </div>

      </div>
    </div>
  </div>
  {% else %}
  <img src="{% static 'images/manager.png'%}" class="img-fluid" alt="Responsive image">

  {% endif %}
  <div class="jumbotron">

    <div class="row">
      <div class="col">
        <div class="title-jumbo">
          <h5>Create a new project</h5>


        </div>
        {% if user.credit %}
        <a href="{% url 'website:create_project' %}" class="btn btn-primary btn-lg btnsmallfont" role="button"><span class="glyphicon glyphicon-plus"></span>   Create a project</a>
        {% else %}
        <button type="button" class="btn btn-primary btn-lg btnsmallfont" data-toggle="modal" data-target="#exampleModalCenter">
            Create a project
        </button>
        <button type="button" class="btn btn-danger btn-lg btnsmallfont" data-toggle="modal" data-target="#test2">
          Watch our demo
        </button>
        <div class="modal fade" id="test2" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
          <div class="modal-dialog modal-dialog-centered video-demo" role="document">
            <div class="modal-content">
              <div class="modal-body">
                <div class="embed-responsive embed-responsive-16by9"><iframe src="https://player.vimeo.com/video/264404960?loop=1&title=0&byline=0&portrait=0" width="1200" height="675" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>">
                  </div>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Create your first project</button>

              </div>
            </div>
          </div>
        </div>
        {% endif %}
      </div>
      <div class="col quote">
        “Who is on a team matters less than how the team members interact, structure their work, and view their contributions"
      </div>
    </div>
  </div>


  <div class="project_list">
    <h3 class="project-title">Project List</h3>
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Project Name</th>
          <th>Team Linked</th>
          <th>Created at</th>
          <th>Open/Close</th>
          <th>edit</th>
        </tr>
    </thead>
    <tbody>

{% for i in project_list %}
      <tr>

        <td>{{i.name}}</td>
        <td>{{i.team_id}}</td>
        <td>{{i.created_at}}</td>
        {% for key,val in status_dict.items %}
          {% if key ==  i.id  %}
            {% if val == True %}
              <td><div class="circle"><span class="glyphicon glyphicon-ok"></span></div></td>
            {% else %}
            <td><div class="circle2"><span class="glyphicon glyphicon-ok"></span></div></td>
            {% endif %}
          {% endif %}
        {% endfor%}

        {% if i.team_id == Null %}
          <td> <a href="{% url 'website:create_team' pk1=i.id %}">Details</a></td>
        {% elif i.team_id and i.team_id.members.count == 0  %}
          <td> <a href="{% url 'registration:team_register3' pk1=i.id %}">Details</a></td>
         {% else %}
         <td> <a href="{% url 'website:ProjectDetails' pk1=i.id %}">Details</a></td>
        {% endif %}

      </tr>
      {% endfor %}
    </tbody>

  </table>

  </div>


</div>

<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <img class="card-img-top" src="{% static "images/manager_happy.png"%}" alt="Card image cap">
      <div class="modal-body">
        <h5>Improve your managerial skills by understanding who is in your team</h5>
        <hr>
        <div class="container">
          <div class="row">
            <div class="col price-value-container">
                  <div class="price-modal-container">
                    <span class="modal-price-title">Price:</span><span class="modal-price">60$</span><span class="modal-Oprice">299$</span><span class="modal-discount">60% off</span>
                  </div>
                  <div class="time-price">
                    <i class="far fa-clock fa-spin"></i>Limited time offer discount
                  </div>
            </div>
          </div>
          <div class="row d-flex text-center button-price">
            <div class="col">
              <a href="{% url 'website:payment' %}" class="btn btn-primary btn-lg btnsmallfont" role="button"><span class="glyphicon glyphicon-plus"></span>  Add Credit Now</a>
            </div>
          </div>
          <div class="row d-flex justify-content-center">
            <div class="col-md-8 includes-section">
                <div class="">Includes: </div>
                <div class="includes-section-list">
                  <div class=""><i class="fas fa-chart-bar"></i> Full team analysis</div>
                  <div class=""><i class="fas fa-users"></i>  Teams up to 7 members</div>
                  <div class=""><i class="fas fa-cogs"></i> Cognitive models explanation</div>
                  <div class=""><i class="fas fa-comments"></i> Communication & motivation tips</div>
                </div>


            </div>
          </div>
        </div>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <a href="{% url 'website:payment' %}" class="btn btn-primary btn-lg btnsmallfont" role="button"><span class="glyphicon glyphicon-plus"></span>  Add Credit Now</a>
      </div>
    </div>
  </div>
</div>

<script type="application/javascript">
    $(document).ready(function(){
        $('#modal-message').modal({show:true});
    });
</script>

{% endblock %}

website/templates/HRnewproject.html
{% extends 'base.html' %}

{% block body %}
<div class="paddingtop100">
  <div class="jumbotron">
    <h1>Welcome to SoftScores.com</h1>
    <h2>Team analytics platfom</h2>
    <h3>Welcome to {{User.username}}, it is your Page</h3>
  </div>
  <div class="container">
    <div class="">
      Create a new project :<a href="{% url 'website:addproject' %}"><span class="glyphicon glyphicon-plus"></span></a>
    </div>

  </div>
</div>




{% endblock %}

website/templates/candidate_index.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block body %}

<div class="container">
  <div class="jumbotron">
    <h3>Welcome to your Employee panel</h3>
    <h4>You can start your survey right away</h4>
  </div>

</div>


{% endblock %}

website/templates/create_project.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block body %}

<div class="container paddingtop100 manager-index">
  <img src="{% static 'images/teambuilding.png'%}" class="img-fluid" alt="Responsive image">

  <div class="jumbotron">
    <div class="row">
      <div class="col">
        <div class="title-jumbo">
          <h3>It is time to create a new project</h3>
          <div>Exemple: Project {% now "d/m/y" %} </div>
        </div>
        <form class="form-inline" method="POST">
            {% csrf_token %}
            {% include 'form-template.html' %}
            <div class="form-group">
              <button type="submit" class="btn btn-primary btn-lg btnsmallfont"> Create a project</button>
            </div>
        </form>
      </div>
      <div class="col quote">
        "“Who is on a team matters less than how the team members interact, structure their work, and view their contributions"
      </div>
    </div>
  </div>

{% endblock %}

website/templates/create_team.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block body %}
<div class="container paddingtop100 manager-index">
<div class="invite-team">
  <img src="{% static 'images/project.png'%}" class="img-fluid" alt="Responsive image">
  <div class="jumbotron">
    <div class="container">
      <div class="row justify-content-center">
        <div class="jumbo-text">
          <h7>Your project has been created, It is time to create a new team for your project</h7>
        </div>
      </div>
      <div class="row justify-content-center">
        <div class="jumbo-button">
          <form class="form-inline" method="POST">
              {% csrf_token %}
              {% include 'form-template.html' %}
              <div class="form-group">
                <button type="submit" class="btn btn-primary">Create</button>
              </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

website/templates/recruitment_index.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<div class="grey_back">


<div class="container candidate_list paddingtop80 padbot30">
    <div class="jumbotron greenback box-shad">
      <div class="container">
        <div class="row justify-content-md-center">

          <h5>Welcome to the recruitment panel</h5>
        </div>
        <div class="row justify-content-md-center">
          <a href="{% url 'registration:applicant_register3' pk1=current_project_id %}" class="btn btn-success" role="button"><span class="glyphicon glyphicon-plus"></span>   Add Applicants</a>
        </div>
      </div>
    </div>


    <div class="row">
        <div class="col-12">
            <div class="card box-shad">
                <h6 class="card-header text-center bg-dark text-white">Candidate that responsed</h6>
                <div class="card-body">
                      {% if app_with_resp|length == 0 %}
                        <div class="no-candidate">
                            No candidate have been invited yet
                        </div>
                      {% else %}
                        <table id="myTable" class="table table-hover tablesorter">
                          <thead>
                              <tr>
                                  <th>First Name</th>
                                  <th>Last Name</th>
                                  <th>Survey Date</th>
                                  <th>Score</th>
                                  <th>Team Score</th>
                                  <th>impact</th>
                                  <th>Details</th>
                              </tr>
                          </thead>
                          <tbody>
                            {% for key, value in appli_score_list.items %}
                              <tr>
                                <td>{{key.first_name}}</td>
                                <td>{{key.last_name}}</td>
                                <td>{{ value.2 }}</td>
                                <td>{{ value.0 }}</td>
                                <td>{{team_score}}</td>
                                <td>{{ value.1 }}</td>
                                <td> <a href="{% url 'website:CandidateDetails' pk1=current_project_id pk2=key.id %}"> Details</a></td>
                              </tr>
                              {% endfor %}
                          </tbody>
                        </table>
                        {% endif %}
                </div>
            </div>

        </div>
    </div>


    <div class="row">
      <div class="col-md-12">
          <div class="card box-shad">
            <h6 class="card-header text-center bg-dark text-white">Invited candidates</h6>
            <div class="card-body">
              {% if app_without_resp|length == 0 %}
                  <div class="no-candidate">
                      No candidate have answered yet
                  </div>
              {% else %}
              <table class="table table-hover">
                <thead>
                    <tr>
                      <th>Email</th>
                      <th>Registration Status</th>
                      <th>Survey Status</th>
                    </tr>
                </thead>
                <tbody>
                    {% for i in app_without_resp %}
                      <tr>
                        <td>{{i}}</td>
                        <td>Waiting for registration</td>
                        <td>Waiting for answers</td>
                      </tr>
                    {% endfor %}
                </tbody>
              </table>
                {% endif %}
          </div>
          </div>
      </div>
    </div>





</div>
</div>
<script type="text/javascript">
$(function(){
  $("#myTable").tablesorter({ sortList: [[5,1]]});
});
</script>

{% endblock %}